pipeline {
    agent any
    stages{
        stage ('git clone') {
            steps {
                git 'https://github.com/Pavan-Kumar-21-01/Jenkins-Zero-To-Hero.git'
            }
        }
        stage ('Maven build') {
            steps{
                sh 'mvn clean package'
            }
        }
        stage ('Artifact') {
            steps {
                echo "building artifact"
            }
        }
    }
}
